USE Libreria

--CONCATENACION

SELECT 'LIBROS ' + NOMBRE FROM LIBROS

SELECT PRECIO_VENTA AS 'PARA PUBLICO', PRECIO_COMPRA AS 'PARA VENDEDOR' FROM LIBROS


--FUNCIONES DE CADENA

--SUBSTRING

SELECT SUBSTRING('hOLA QUE TAL', 9, 1) --PRIMERO PONES EL NOMBRE DE DONDE SACAS LA SUBSTRING, 
--LUEGO EL NUMERO DONDE COMIENZAS Y AL FINAL LA CANTIDAD DE CARACTERES QUE SELECCIONARAS


--STR
SELECT STR(123)--PASAR A CADENA

--STUFF: REEMPLAZA PARTE DE UNA CADENA

SELECT STUFF('TUTORIAL MARK', 10, 4, 'VIKING') 

--LEN: LONGITUD DE CADENA

SELECT LEN('TUTORIALES VIKING')

--CHAR: CONVERSION A CODIGO

SELECT CHAR(68)


--LOWER Y UPPER:

SELECT LOWER ( 'TUTORIAL') PASAR A MINUSCULA
SELECT UPPER('TUTORIAL') PASAR A MAYUSCULA

--RTRIM Y LTRIM: QUITAR ESPACIOS
SELECT LTRIM ('        MARK')
SELECT RTRIM ('        MARK              ')

--REPLACE: REEMPLAZAR CADENAS

SELECT REPLACE ('HOLA QUE TAL TODO FINO', 'FINO', 'BIEN')

--REVERSE: REVERSION DE PALABRAS

SELECT REVERSE('ARROZ')

--PATINDEX: ENCUENTRA COINCIDENCIA Y TE DEVUELVE EL NUMERO DONDE INICIA

SELECT PATINDEX('%FINO%','HOLA QUE TAL TODO FINO')

--REPLICATE: MULTIPLICA LA CADENA POR X NUMERO

SELECT REPLICATE('KRAM ', 3)

--SPACE: PONE ESPACIO ENTRE PALABRAS

SELECT 'TUTORIALES' + SPACE(4)+'VIKING'